---
title: "GSEA_RankedList_Generation"
output: html_document
date: "2023-02-02"
---

```{r}
library(Seurat)
library(dplyr)
```

```{r}
subtype <- readRDS("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/objects/Rerun_Mouse5TG_StromalsOnly_AnnotatedObject6_21PCs_NoLib_FIXEDLIBRARIES_6.rds")
mscolcs <- subset(subtype, subset = celltypes_ECsubbed %in% c("MSCs", "OLCs"))

mscolcs <- ScaleData(mscolcs)
mscolcs <- FindVariableFeatures(mscolcs, nfeatures = 2000)
mscolcs <- RunPCA(mscolcs, npcs = 10)
mscolcs <- FindNeighbors(mscolcs, dims = 1:10)
mscolcs <- FindClusters(mscolcs, resolution = 0.2)
mscolcs <- RunUMAP(mscolcs, dims = 1:10)
mscolcs <- subset(mscolcs, subset = seurat_clusters %in% c("0", "1", "2", "3", "4", "5"))
DimPlot(mscolcs)
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/MSCOLCs_UMAP.png", height = 4, width = 5)

```

```{r}
markers <- FindMarkers(mscolcs, ident.1 = "5", ident.2 = c("0", "1", "2", "3", "4"), min.pct = 0.25, logfc.threshold = 0.25)

# If ident.1 = disease and ident.2 = control, then POSITIVE logFC means that the gene is upregulated in disease relative to control and NEGATIVE means the gene is downregulated in disease relative to control
```
# Generate ranked list
```{r}

#markers <- replace(markers$p_val_adj, markers$p_val_adj == 0, 0.0000000000000000000000000000000000000000000000000000001281612)
# Generate rank score (adapted from Patrick's DESeq2/GSEA script)
rank.score <- sign(markers$avg_log2FC) * -log10(markers$p_val_adj)
# Generate gene list
genes <- rownames(markers)
# Put into df
rank.df <- data.frame(genes, rank.score)
rownames(rank.df) <- rank.df$genes

# Fixing infinity values caused by infinitely small zero p values. Just assuming each gene has +1 rank score.
# for (i in 1:72) {
#   rank.df$rank.score[i] <- 373 - i
# }

# Write out ranked list
write.table(rank.df, "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/GSEA/rankedLists/MSCOLCs_Cluster5_vsOthers_forGSEA.rnk",
            sep = "\t",
            quote = F,
            row.names = F,
            col.names = F)


rank.df
```

