---
title: "Making_GSEA_Input"
output: html_document
date: "2023-01-30"
---

Load in necessary packages, set scientific notation and ggplot theme
```{r set-env, message=FALSE, warning=FALSE, results='hide'}
rm(list=ls())
library(DESeq2)
library(apeglm)
library(rtracklayer)
library(tidyverse)
library(ComplexHeatmap)
library(glue)
library(ggrepel)
library(EnhancedVolcano)
library(ggpubr)
library(paletteer)

options(scipen = 999)

# Set figure base theme
theme_set(
  theme_gray() +
  theme(axis.line = element_line(size = 0.5,  color = "black"),
        panel.background = element_rect(fill = NA, size = rel(14)),
        panel.grid.minor = element_line(color = NA),
        axis.text = element_text(size = 12,  color = "black"),
        axis.title = element_text(size = 14),
        axis.ticks = element_line(size = 0.75),
        title = element_text(size = 16),
        plot.title = element_text(hjust = 0.5)
        )
  )
```

```{r}
library(Seurat)
library(Matrix)
library(tibble)
```
# Read in stromals
```{r}
stromals <- readRDS("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/objects/Rerun_Mouse5TG_StromalsOnly_AnnotatedObject6_21PCs_NoLib_FIXEDLIBRARIES_6.rds")
healthy.fibros <- subset(stromals, subset = celltype_cond == "Healthy Fibroblasts")
myeloma.fibros <- subset(stromals, subset = celltype_cond == "MM Fibroblasts")
```
# Write matrices
```{r}
matrix <- as.data.frame(GetAssayData(object = healthy.fibros, slot = "counts"))
matrix <- matrix + 1
write.table(matrix, '/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/healthyFibroblast_counts.txt', sep = "\t")

matrix <- as.data.frame(GetAssayData(object = myeloma.fibros, slot = "counts"))
matrix <- matrix + 1
write.table(matrix, '/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/myelomaFibroblast_counts.txt', sep = "\t")
```
# Make other metadata
# Need a metadata file with 3 columns...1st is cell names, 2nd is the condition (so in this case, just "myeloma" or "healthy", and 3rd is "paired end")
```{r}
metadata <- as.data.frame(colnames(healthy.fibros))
colnames(metadata) <- "V1"
metadata$V2 <- "Healthy"
metadata$V3 <- "paired-end"
head(metadata)

write.table(metadata, "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/healthyFibroblast_conditions.txt")

###

metadata <- as.data.frame(colnames(myeloma.fibros))
colnames(metadata) <- "cellnames"
metadata$condition <- "Myeloma"
metadata$sequencing <- "paired-end"
head(metadata)

write.table(metadata, "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/myelomaFibroblast_conditions.txt")
```
# DESEQ FUNCTION
```{r}
deseq2_exe <- function(x_counts_input, y_counts_input,
                       x_conditions_input, y_conditions_input,
                       gencode_gene_list = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/gencode.v42.primary_assembly.basic.annotation.gtf.gz") {
  
  x_counts <- read.table(file = x_counts_input) # deleted header = F
  colnames(x_counts) <- gsub('\\.', '-', colnames(x_counts)) # need to do this replace because for some reason the - is being replaced before this??? no idea where???

  y_counts <- read.table(file = y_counts_input)
  colnames(y_counts) <- gsub('\\.', '-', colnames(y_counts)) # need to do this replace because for some reason the - is being replaced before this??? no idea where???

  x_conditions <- read.table(x_conditions_input)
  colnames(x_conditions) <- c("sample", "condition", "type")
  rownames(x_conditions) <- x_conditions$sample
  x_conditions <- x_conditions[,-1]
  
  y_conditions <- read.table(y_conditions_input)
  colnames(y_conditions) <- c("sample", "condition", "type")
  rownames(y_conditions) <- y_conditions$sample
  y_conditions <- y_conditions[,-1]

  # Create condition comparison matrix and factorize condition matrix variables
  y_vs_x_conditions <- rbind(x_conditions, y_conditions)
  y_vs_x_conditions$condition <- factor(y_vs_x_conditions$condition,
                                        levels = c(x_conditions[1,1], y_conditions[1,1]))
  y_vs_x_conditions$type <- factor(y_vs_x_conditions$type)
  
  # Create count comparison matrix
  y_vs_x_counts <- cbind(x_counts, y_counts)

  # To refine analysis, restrict the counts matrix to CDS genes in GENCODE v42 GTF
  # and then remove any mitochondrial genes
  gencode_genes <- import(gencode_gene_list)
  gencode_genes <- unique(gencode_genes[gencode_genes$type == "CDS"]$gene_name)
  gencode_genes <- gencode_genes[!str_detect(string = gencode_genes, pattern = "^MT-")]
  
  y_vs_x_counts <- y_vs_x_counts %>%
                     dplyr::filter(rownames(y_vs_x_counts) %in% gencode_genes)
  
  # Quick first hard filter to remove genes with little expression across all samples
  # Remove all genes with mean expression < median(all_per_gene_exp_mean) / 10
  per_gene_exp_mean <- y_vs_x_counts %>%
                         dplyr::mutate(exp_mean = round(rowSums(y_vs_x_counts) / ncol(y_vs_x_counts),
                                                        digits = 0)) %>%
                         dplyr::select(exp_mean) %>%
                         purrr::as_vector() %>%
                         as.numeric()
  
  y_vs_x_counts <- y_vs_x_counts %>%
                     dplyr::filter(rowSums(y_vs_x_counts) / ncol(y_vs_x_counts) > round(median(per_gene_exp_mean) / 10,
                                                                                        digits = 0))
  
  # Convert counts matrix and conditions file into DESeq2 object
  y_vs_x_counts_deseq_obj <- DESeqDataSetFromMatrix(countData = y_vs_x_counts,
                                                    colData = y_vs_x_conditions,
                                                    design = ~ condition)
  
  # Run DESeq2
  y_vs_x_counts_deseq_obj <- DESeq(object = y_vs_x_counts_deseq_obj)

  return(y_vs_x_counts_deseq_obj)
}
```
# Running the function
```{r}
x_counts <- "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/healthyFibroblast_counts.txt"
y_counts <-"/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/myelomaFibroblast_counts.txt"
  
x_conditions <- "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/healthyFibroblast_conditions.txt"
y_conditions <- "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/myelomaFibroblast_conditions.txt"

diff_exp_obj <- deseq2_exe(x_counts_input = x_counts,
                           y_counts_input = y_counts,
                           x_conditions_input = x_conditions,
                           y_conditions_input = y_conditions)
```

```{r}
x_counts_input <- "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/healthyFibroblast_counts.txt"
y_counts_input <-"/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/myelomaFibroblast_counts.txt"
  
x_conditions_input <- "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/healthyFibroblast_conditions.txt"
y_conditions_input <- "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/myelomaFibroblast_conditions.txt"

# Read in two sets of raw count matrix from featureCounts output
x_counts <- read.table(file = x_counts_input) # deleted header = F
colnames(x_counts) <- gsub('\\.', '-', colnames(x_counts)) # need to do this replace because for some reason the - is being replaced before this??? no idea where???

y_counts <- read.table(file = y_counts_input)
colnames(y_counts) <- gsub('\\.', '-', colnames(y_counts))

x_conditions <- read.table(x_conditions_input)
colnames(x_conditions) <- c("sample", "condition", "type")
rownames(x_conditions) <- x_conditions$sample
x_conditions <- x_conditions[,-1]

y_conditions <- read.table(y_conditions_input)
colnames(y_conditions) <- c("sample", "condition", "type")

rownames(y_conditions) <- y_conditions$sample
y_conditions <- y_conditions[,-1]
###
```

```{r}
# Create condition comparison matrix and factorize condition matrix variables
y_vs_x_conditions <- rbind(x_conditions, y_conditions)
y_vs_x_conditions$condition <- factor(y_vs_x_conditions$condition)
y_vs_x_conditions$type <- factor(y_vs_x_conditions$type)

# Create count comparison matrix
y_vs_x_counts <- cbind(x_counts, y_counts)

# To refine analysis, restrict the counts matrix to CDS genes in GENCODE v42 GTF
# and then remove any mitochondrial genes
gencode_genes <- import(gencode_gene_list)
gencode_genes <- unique(gencode_genes[gencode_genes$type == "CDS"]$gene_name)
gencode_genes <- gencode_genes[!str_detect(string = gencode_genes, pattern = "^MT-")]

y_vs_x_counts <- y_vs_x_counts %>%
                   dplyr::filter(rownames(y_vs_x_counts) %in% gencode_genes)

# Quick first hard filter to remove genes with little expression across all samples
# Remove all genes with mean expression < median(all_per_gene_exp_mean) / 10
per_gene_exp_mean <- y_vs_x_counts %>%
                       dplyr::mutate(exp_mean = round(rowSums(y_vs_x_counts) / ncol(y_vs_x_counts),
                                                      digits = 0)) %>%
                       dplyr::select(exp_mean) %>%
                       purrr::as_vector() %>%
                       as.numeric()

y_vs_x_counts <- y_vs_x_counts %>%
                   dplyr::filter(rowSums(y_vs_x_counts) / ncol(y_vs_x_counts) > round(median(per_gene_exp_mean) / 10,
                                                                                      digits = 0))

# Convert counts matrix and conditions file into DESeq2 object
y_vs_x_counts_deseq_obj <- DESeqDataSetFromMatrix(countData = y_vs_x_counts,
                                                  colData = y_vs_x_conditions,
                                                  design = ~ condition)

# Run DESeq2
y_vs_x_counts_deseq_obj <- DESeq(object = y_vs_x_counts_deseq_obj)
```

```{r}
setdiff(rownames(y_vs_x_conditions),colnames(y_vs_x_counts))

length(rownames(y_vs_x_conditions))
length(colnames(y_vs_x_counts))

head(rownames(y_vs_x_conditions))
head(colnames(y_vs_x_counts))
```

