---
title: "MSC_AdipoOsteo_Differentiation_Analysis"
output: html_document
date: "2023-03-29"
---

# Libraries
```{r}
library(Seurat)
library(ggplot2)
library(circlize)
library(ComplexHeatmap)
library(ggpubr)
library(grid)
library(gridExtra)

colors <- c("#F8766D", "#B79F00", "#00BA38", "#00BFC4", "#619CFF", "#F564E3")
```
# Load in stromal data
```{r}
stromals <- readRDS("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/Rerun_Mouse5TG_StromalsOnly_AnnotatedObject6_21PCs_NoLib_FIXEDLIBRARIES_6.rds")
```
# Subset celltype
```{r}
subtype <- subset(stromals, subset = celltypes_ECsubbed %in% c("MSCs, OLCs"))
```
# Standard workflow
# Doing this because we want the most variable genes for the fibroblasts specifically, not for the entire dataset
```{r}
subtype <- ScaleData(subtype)
subtype <- FindVariableFeatures(subtype, nfeatures = 2000)
subtype <- RunPCA(subtype, npcs = 20)
subtype <- FindNeighbors(subtype, dims = 1:20)
subtype <- FindClusters(subtype, resolution = 0.2)
subtype <- RunUMAP(subtype, dims = 1:20)
DimPlot(subtype, split.by = "case.control", ncol = 2)
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLCs_Subclustered_ConditionSplit_UMAP_Horizontal.png", height = 4, width = 8)
```
# Differential abundance
```{r}
healthy.subtype <- subset(subtype, subset = case.control == "Healthy")
myeloma.subtype <- subset(subtype, subset = case.control == "Myeloma")

table(healthy.subtype@meta.data$seurat_clusters)/sum(table(healthy.subtype@meta.data$seurat_clusters))
table(myeloma.subtype@meta.data$seurat_clusters)/sum(table(myeloma.subtype@meta.data$seurat_clusters))
table(subtype@meta.data$seurat_clusters)/sum(table(subtype@meta.data$seurat_clusters))

```

```{r}
# Osteo genes
VlnPlot(subtype, features = c("Bglap", "Bglap2", "Col1a1", "Sparc"), ncol = 4, split.by = "case.control")
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLCs_OsteoGenes_CaseControl_ViolinPlots.png", width = 15, height = 3.5)

VlnPlot(subtype, features = c("Bglap", "Col1a1", "Sparc"), ncol = 3,
        col = colors)
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLCs_OsteoGenes_NotSplit_ViolinPlots.png", width = 9, height = 3)

# Adipo genes
VlnPlot(subtype, features = c("Lepr", "Adipoq", "Lpl", "Mgp"), ncol = 4, split.by = "case.control")
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLCs_AdipoGenes_CaseControl_ViolinPlots.png", width = 15, height = 3.5)

VlnPlot(subtype, features = c("Lpl", "Mgp", "Adipoq"), ncol = 3, col = colors)
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLCs_AdipoGenes_NotSplit_ViolinPlots.png", width = 9, height = 3)

# Osteoblast differentiation inhibition genes
VlnPlot(subtype, features = c("Runx2", "Ephb4", "Sp7"), ncol = 3, col = colors)
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLCs_OsteoInhib_CaseControl_ViolinPlots.png", width = 9, height = 3)
```

```{r}
# Adipo-MSCs
FeaturePlot(subtype, features = c("Lpl"), split.by = "case.control")

# Osteo-MSCs 1
FeaturePlot(subtype, features = c("Wif1"), split.by = "case.control")

# Osteo-MSCs 2
FeaturePlot(subtype, features = c("Spp1"), split.by = "case.control")

# Osteos proper 3
FeaturePlot(subtype, features = c("Bglap"), split.by = "case.control")

# MSC differentiation FeaturePlot
FeaturePlot(subtype, features = c("Lpl",
                                  "Wif1",
                                  "Spp1",
                                  "Bglap"), split.by = "case.control")
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLC_PolarizedDifferentiationGenes.png", width = 8, height = 16)
# And VlnPlots
VlnPlot(subtype, features = c("Lpl", "Wif1", "Spp1", "Bglap"), ncol = 4)
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLC_PolarizedDifferentiationGenes_ViolinPlots.png", width = 12, height = 3.5)


#Osteo
FeaturePlot(subtype, features = c("Adipoq"), split.by = "case.control")
FeaturePlot(subtype, features = c("Lpl"), split.by = "case.control")
FeaturePlot(subtype, features = c("Mgp"), split.by = "case.control")
FeaturePlot(subtype, features = c("Lepr"), split.by = "case.control")

# Osteo genes
FeaturePlot(subtype, features = c("Bglap", "Runx2",
                                  "Col1a1", "Sparc"), ncol = 2, split.by = "case.control")
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/speebo.png", width = 12, height = 16)

# Adipo genes
FeaturePlot(subtype, features = c("Adipoq", "Lpl",
                                  "Lepr", "Cebpa"), ncol = 2, split.by = "case.control")
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLCs_AdipoGenes_CaseControl_FeaturePlots.png", width = 12, height = 16)
```

```{r}
# Igor cluster vs our cluster parallel
VlnPlot(subtype, features = c("Mgp", "Lpl", "Wif1", 
                              "Spp1", "Ibsp", "Col16a1",
                              "Fbn1", "Igf1", "Bglap"), ncol = 3)
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/MSCOLCs_DolgalevDifferentiationGenes_VlnPlots.png", width = 12, height = 10.5)
DimPlot(subtype, split.by = "case.control")

VlnPlot(subtype, features = c("Mgp", "Lpl", "Wif1", "Spp1", "Ibsp"), ncol = 5)

```

```{r}
# Pro Bone
FeaturePlot(subtype, features = c("Bglap", "Runx2"), ncol = 2, split.by = "case.control")
FeaturePlot(subtype, features = c("Col1a1", "Sparc"), ncol = 2, split.by = "case.control")
# Pro Fat
FeaturePlot(subtype, features = c("Lepr", "Adipoq"), ncol = 2, split.by = "case.control")
FeaturePlot(subtype, features = c("Lpl", "Cebpa"), ncol = 2, split.by = "case.control")

```


```{r}
# P - Cluster 1
VlnPlot(subtype, features = c("Mgp", "Gpx3", "Serping1", "Lepr", "Tmem176b", 
                              "Igfbp5", "Malat1", "C1ra", "C4b", "Epas1"), ncol = 5)
# P - Cluster 2
VlnPlot(subtype, features = c("Lpl", "Scp2", "Fstl1", "Rgcc", "Mrps6", 
                              "Pdzrn4", "Mmd", "Np2", "Slc5a3", "Angpt1"), ncol = 5)
# P - Cluster 3
VlnPlot(subtype, features = c("Col8a1", "Kcnk2", "Ndnf", "Palld", "Tnfrsf19", 
                              "Cldn10", "Slc20a2", "Limch1", "Fhl1"), ncol = 5)
# P - Cluster 4
VlnPlot(subtype, features = c("Spp1", "Col1a1", "Col13a1", "Mmp13", "Ifitm5", 
                              "Serpine2", "Mef2c", "Ibsp", "Itgb5", "Aqp1"), ncol = 5)
# Osteo - Cluster 1
VlnPlot(subtype, features = c("Tnn", "Postn", "Col16a1", "Lrrc15", "Angptl2", 
                              "Mmp14", "Alpl", "Ncam1", "Mmp13", "Col5a1"), ncol = 5)
# Osteo - Cluster 2
VlnPlot(subtype, features = c("Igfbp7", "Igfbp6", "Mgp", "Fbn1", "Thbs4", 
                              "Prelp", "Igf1", "Lbp", "Meg3", "Fbln2"), ncol = 5)
# Osteo - Cluster 3
VlnPlot(subtype, features = c("Ifitm", "Col11a2", "Car3", "Cgref1", "Bglap", 
                              "Slc36a2", "Cpz", "Sgm2", "Smpd3", "Mef2c"), ncol = 5)

DimPlot(subtype)

# Full set of bone cells
bone.subset <- subset(stromals, subset = celltypes_ECsubbed %in% c("MSCs", "OLCs"))
bone.subset <- ScaleData(bone.subset)
bone.subset <- FindVariableFeatures(bone.subset, nfeatures = 2000)
bone.subset <- RunPCA(bone.subset, npcs = 5)

bone.subset <- FindNeighbors(bone.subset, dims = 1:5)
bone.subset <- FindClusters(bone.subset, resolution = 0.12)
bone.subset <- RunUMAP(bone.subset, dims = 1:5)

DimPlot(bone.subset, cols = c("#F8766D", "#B79F00", "#00BA38", "#00BFC4", "#619CFF", "#F564E3", "#C77CFF"), split.by = "case.control")

# Pseudotime directions - row 1 = bone, row 2 = adipo
VlnPlot(bone.subset, features = c("Bglap", "Runx2", "Col1a1", "Sparc",
                                  "Lepr", "Adipoq", "Lpl", "Cebpa"), ncol = 4)
VlnPlot(subtype, features = c("Bglap", "Runx2", "Col1a1", "Sparc",
                                  "Lepr", "Adipoq", "Lpl", "Cebpa"), ncol = 4)
# Igor cluster vs our cluster parallel
VlnPlot(subtype, features = c("Mgp", "Lpl", "Wif1", "Spp1", "Ibsp",
                                  "Col16a1", "Tnn", "Fbn1", "Igf1",
                                  "Bglap", "Car3"), ncol = 4)
DimPlot(bone.subset, cols = c("#F8766D", "#B79F00", "#00BA38", "#00BFC4", "#619CFF", "#F564E3", "#C77CFF"), split.by = "case.control")
DimPlot(bone.subset, group.by = "celltypes_ECsubbed", split.by = "case.control")


VlnPlot(bone.subset, features = c("Mgp", "Lpl", "Wif1", "Spp1", "Ibsp"), ncol = 5, split.by = "case.control")

# Osteo - Cluster 1
VlnPlot(subtype, features = c("Tnn", "Postn", "Col16a1", "Lrrc15", "Angptl2", 
                              "Mmp14", "Alpl", "Ncam1", "Mmp13", "Col5a1"), ncol = 5)
# Osteo - Cluster 2
VlnPlot(subtype, features = c("Igfbp7", "Igfbp6", "Mgp", "Fbn1", "Thbs4", 
                              "Prelp", "Igf1", "Lbp", "Meg3", "Fbln2"), ncol = 5)
# Osteo - Cluster 3
VlnPlot(subtype, features = c("Sparc", "Col11a2", "Car3", "Cgref1", "Bglap", 
                              "Runx2", "Bglap2", "Col1a2", "Smpd3", "Mef2c"), ncol = 5)

VlnPlot(bone.subset, features = c("Tnn", "Postn", "Col16a1", "Lrrc15", "Angptl2", 
                              "Mmp14", "Alpl", "Ncam1", "Mmp13", "Col5a1"), ncol = 5, split.by = "case.control")
# Osteo - Cluster 2
VlnPlot(bone.subset, features = c("Igfbp7", "Igfbp6", "Mgp", "Fbn1", "Thbs4", 
                              "Prelp", "Igf1", "Lbp", "Meg3", "Fbln2"), ncol = 5, split.by = "case.control")
# Osteo - Cluster 3
VlnPlot(bone.subset, features = c("Ifitm", "Col11a2", "Car3", "Cgref1", "Bglap", 
                              "Slc36a2", "Cpz", "Sgm2", "Smpd3", "Mef2c"), ncol = 5, split.by = "case.control")

# Aggregated good bone markers
# O1
VlnPlot(subtype, features = c("Bglap", "Bglap2", "Sparc", "Col1a2", "Mef2c"), split.by = "case.control")
# O2
VlnPlot(subtype, features = c("Mmp14", "Alpl", "Ncam1", "Mmp13"), split.by = "case.control")
# O3
VlnPlot(subtype, features = c("Igfbp7", "Igf1", "Fbn1", "Mgp", "Prelp", "Lbp"))
VlnPlot(subtype, features = c("Igfbp7", "Igf1", "Fbn1", "Mgp", "Prelp", "Lbp"), split.by = "case.control")

# Get cluster subset %s
table(subtype.healthy@meta.data$seurat_clusters)/sum(table(subtype.healthy@meta.data$seurat_clusters))
table(subtype.myeloma@meta.data$seurat_clusters)/sum(table(subtype.myeloma@meta.data$seurat_clusters))
```
