---
title: "Rerun_5TG_Stromal_DiffusionMap"
output: html_document
date: "2022-11-30"
---

```{r}
library(Seurat)
```

```{r}
mouseBM <- readRDS("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/Rerun_Mouse5TG_IntegratedObject5_Annotated.rds")
stromals <- subset(mouseBM, subset = celltypes == "immune cells", invert = T)
```

# Standard workflow time
```{r}
DefaultAssay(stromals) <- "integrated"

stromals <- ScaleData(stromals)
stromals <- FindVariableFeatures(stromals, nfeatures = 2000)
stromals <- RunPCA(stromals, npcs = 25)
ElbowPlot(
  object = stromals, 
  ndims = 25
) +
  geom_abline(
    aes(intercept = 1.75, slope = 0, color = "red"),
    show.legend = FALSE
  )
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/5TG_Stromals_ElbowPlot.png", width = 8, height = 6)
# Choosing PCs based on elbow point

# Determine percent of variation associated with each PC
pct <- stromals[["pca"]]@stdev / sum(stromals[["pca"]]@stdev) * 100
cumu <- cumsum(pct) # Calculate cumulative percents for each PC

# Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
co1 <- which(cumu > 90 & pct < 5)[1]
# Determine the difference between variation of PC and subsequent PC
co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1

if (co1 < co2) {
  n_pc <- co1
  print(paste0("the elbow PC is ", co1))
} else {
  n_pc <- 2
  print(paste0("the elbow point is ", co2))
}

stromals <- FindNeighbors(stromals, dims = 1:21)
stromals <- FindClusters(stromals, resolution = 0.12)
stromals <- RunUMAP(stromals, dims = 1:21)
DimPlot(stromals, label = T)
DimPlot(stromals, group.by = "celltypes")
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/5TG_Stromals_AnnotatedUMAP_21PCs.png", width = 8, height = 6)

saveRDS(stromals, "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/Rerun_Mouse5TG_StromalsOnly_AnnotatedObject6_21PCs_NoLib6.rds")
```
# Case Control breakdown
```{r}
myeloma <- subset(stromals, subset = case.control == "myeloma")
healthy <- subset(stromals, case.control == "healthy")

DimPlot(myeloma, group.by = "celltypes")
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/5TG_Stromal_Myelomas_AnnotatedUMAP.png", width = 8, height = 6)
DimPlot(healthy, group.by = "celltypes")
ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/5TG_Stromals_Healthy_AnnotatedUMAP.png", width = 8, height = 6)

table(myeloma@meta.data$celltypes)
table(healthy@meta.data$celltypes)

Idents(stromals) <- "case.control"
myelomas <- WhichCells(stromals, idents = c("myeloma"))
healthies <- WhichCells(stromals, idents = c( "healthy"))

p1 <- DimPlot(stromals, cells.highlight = list(myelomas), cols.highlight = c("salmon"), cols = "lightsteelblue", sizes.highlight = 1, pt.size = 1, order = T) + 
  scale_color_manual(labels = c("Myeloma", "Healthy"), values = c("lightsteelblue", "salmon"))
p2 <- DimPlot(stromals, cells.highlight = list(healthies), cols.highlight = c("lightseagreen"), cols = "lightsteelblue", sizes.highlight = 1, pt.size = 1) +
  scale_color_manual(labels = c("Healthy", "Myeloma"), values = c("lightsteelblue", "lightseagreen"))
both <- grid.arrange(p1, p2, nrow = 1)
both
ggsave(plot = both, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/CaseControl_Finalish_UMAPs.png", height = 6, width = 12)
```
# More discrete condition cluster breakdown
```{r}
stromals@meta.data$testes <- stromals@meta.data$case.control
stromals@meta.data <- stromals@meta.data %>% 
  mutate(testes = ifelse(case.control == "healthy" & celltypes == "MSCs", "healthy.MSCs", testes)) %>%
  mutate(testes = ifelse(case.control == "myeloma" & celltypes == "MSCs", "myeloma.MSCs", testes)) %>%
  mutate(testes = ifelse(case.control == "healthy" & celltypes == "OLCs", "healthy.OLCs", testes)) %>%
  mutate(testes = ifelse(case.control == "myeloma" & celltypes == "OLCs", "myeloma.OLCs", testes)) %>%
  mutate(testes = ifelse(case.control == "healthy" & celltypes == "Fibroblasts", "healthy.fibros", testes)) %>%
  mutate(testes = ifelse(case.control == "myeloma" & celltypes == "Fibroblasts", "myeloma.fibros", testes)) %>%
  mutate(testes = ifelse(case.control == "healthy" & celltypes == "Chondrocytes", "healthy.chondros", testes)) %>%
  mutate(testes = ifelse(case.control == "myeloma" & celltypes == "Chondrocytes", "myeloma.chondros", testes)) %>%
  mutate(testes = ifelse(case.control == "healthy" & celltypes == "Pericytes", "healthy.peris", testes)) %>%
  mutate(testes = ifelse(case.control == "myeloma" & celltypes == "Pericytes", "myeloma.peris", testes)) %>%
  mutate(testes = ifelse(case.control == "healthy" & celltypes == "ECs", "healthy.ECs", testes)) %>%
  mutate(testes = ifelse(case.control == "myeloma" & celltypes == "ECs", "myeloma.ECs", testes))
  
table(stromals@meta.data$testes)

Idents(stromals) <- "testes"
healthy.msc <- WhichCells(stromals, idents = c("healthy.MSCs"))
healthy.olc <- WhichCells(stromals, idents = c("healthy.OLCs"))
healthy.fibro <- WhichCells(stromals, idents = c("healthy.fibros"))
healthy.chondro <- WhichCells(stromals, idents = c("healthy.chondros"))
healthy.peri <- WhichCells(stromals, idents = c("healthy.peris"))
healthy.ecs <- WhichCells(stromals, idents = c("healthy.ECs"))

myeloma.msc <- WhichCells(stromals, idents = c("myeloma.MSCs"))
myeloma.olc <- WhichCells(stromals, idents = c("myeloma.OLCs"))
myeloma.fibro <- WhichCells(stromals, idents = c("myeloma.fibros"))
myeloma.chondro <- WhichCells(stromals, idents = c("myeloma.chondros"))
myeloma.peri <- WhichCells(stromals, idents = c("myeloma.peris"))
myeloma.ecs <- WhichCells(stromals, idents = c("myeloma.ECs"))

p1 <- DimPlot(stromals, cells.highlight = list(healthy.msc, healthy.olc, healthy.fibro, healthy.chondro, healthy.peri, healthy.ecs),
              cols.highlight = c("salmon", "brown", "black", "green", "red", "blue"), cols = "lightsteelblue", sizes.highlight = 1, pt.size = 1, order = T) + 
  scale_color_manual(labels = c("Myeloma", "Healthy MSCs", "Healthy OLCs", "Healthy Fibroblasts", "Healthy Chondrocytes", "Healthy Pericytes", "Healthy ECs"), values = c("lightsteelblue", "salmon", "darkcyan", "green", "black", "red", "blue"))
p1
```



# Feature Plots
```{r}
DefaultAssay(stromals) <- "RNA"
library(gridExtra)
library(scico)
library(RColorBrewer)

# MSCs
msc1 <- FeaturePlot(stromals, features = "Lepr") 
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Lepr_FeaturePlot5.png", height = 6, width = 6)
msc2 <- FeaturePlot(stromals, features = "Adipoq") + scale_fill_scico(palette = 'lajolla') 
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Adipoq_FeaturePlot5.png", height = 6, width = 6)
msc3 <- FeaturePlot(stromals, features = "Cxcl12") + scale_fill_scico(palette = 'lajolla') 

msc.features <- grid.arrange(msc1, msc2, msc3, nrow = 1)
ggsave(plot = msc.features, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/MSC_FeaturePlotGrid.png", height = 6, width = 15)


# OLCs
olcs1 <- FeaturePlot(stromals, features = "Bglap")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Bglap_FeaturePlot5.png", height = 6, width = 6)
olcs2 <- FeaturePlot(stromals, features = "Spp1")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Spp1_FeaturePlot5.png", height = 6, width = 6)
olcs3 <- FeaturePlot(stromals, features = "Sp7")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Spp1_FeaturePlot5.png", height = 6, width = 6)

olc.features <- grid.arrange(olcs1, olcs2, olcs3, nrow = 1)
ggsave(plot = olc.features, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/OLC_FeaturePlotGrid.png", height = 6, width = 15)

# Fibros
fibros1 <- FeaturePlot(stromals, features = "S100a4")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/S100a4_FeaturePlot5.png", height = 6, width = 6)
fibros2 <- FeaturePlot(stromals, features = "Fn1")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Fn1_FeaturePlot5.png", height = 6, width = 6)
fibros3 <- FeaturePlot(stromals, features = "Dcn")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Dcn_FeaturePlot5.png", height = 6, width = 6)

fibros.features <- grid.arrange(fibros1, fibros2, fibros3, nrow = 1)
ggsave(plot = fibros.features, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Fibros_FeaturePlotGrid.png", height = 6, width = 15)

# Chondrocytes 
chondros1 <- FeaturePlot(stromals, features = "Col2a1")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Col2a1_FeaturePlot5.png", height = 6, width = 6)
chondros2 <- FeaturePlot(stromals, features = "Sox9")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Sox9_FeaturePlot5.png", height = 6, width = 6)
chondros3 <- FeaturePlot(stromals, features = "Acan")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Acan_FeaturePlot5.png", height = 6, width = 6)

chondros.features <- grid.arrange(chondros1, chondros2, chondros3, nrow = 1)
ggsave(plot = chondros.features, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Chondros_FeaturePlotGrid.png", height = 6, width = 15)

# Pericytes
peris1 <- FeaturePlot(stromals, features = "Acta2")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Acta2_FeaturePlot5.png", height = 6, width = 6)
peris2 <- FeaturePlot(stromals, features = "Myh11")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Myh11_FeaturePlot5.png", height = 6, width = 6)
peris3 <- FeaturePlot(stromals, features = "Mcam")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Mcam_FeaturePlot5.png", height = 6, width = 6)

peris.features <- grid.arrange(peris1, peris2, peris3, nrow = 1)
ggsave(plot = peris.features, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Pericytes_FeaturePlotGrid.png", height = 6, width = 15)

# ECs
ecs1 <- FeaturePlot(stromals, features = "Cdh5")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Cdh5_FeaturePlot5.png", height = 6, width = 6)
ecs2 <- FeaturePlot(stromals, features = "Cd34")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Kdr_FeaturePlot5.png", height = 6, width = 6)
ecs3 <- FeaturePlot(stromals, features = "Pecam1")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Emcn_FeaturePlot5.png", height = 6, width = 6)
ecs4 <- FeaturePlot(stromals, features = "Kdr")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Emcn_FeaturePlot5.png", height = 6, width = 6)
ecs5 <- FeaturePlot(stromals, features = "Emcn")
#ggsave("/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Emcn_FeaturePlot5.png", height = 6, width = 6)

# EC subpopulations - Arterial and Sinusoidal
ecs6 <- FeaturePlot(stromals, features = "Flt4") + ggtitle("Flt4 (Vegfr-3)") 
ecs7 <- FeaturePlot(stromals, features = "Ly6a") + ggtitle("Ly6a (Sca-1)")
ecs8 <- FeaturePlot(stromals, features = "Cxcl12") 
ecs9 <- FeaturePlot(stromals, features = "Il6st") 

ecs.features <- grid.arrange(ecs1, ecs2, ecs3, nrow = 1)
ggsave(plot = ecs.features, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/ECs_FeaturePlotGrid.png", height = 3, width = 9)

ecs.subtypes <- grid.arrange(ecs6, ecs7, ecs8, ecs9, nrow = 1)
ggsave(plot = ecs.subtypes, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/ECSubtypes_FeaturePlotGrid.png", height = 3, width = 12)
```
# Violins
```{r}
DefaultAssay(stromals) <- "RNA"
Idents(stromals) <- factor(Idents(stromals), levels = c("Fibroblasts", "Chondrocytes", "MSCs", "OLCs","Pericytes", "Arterial ECs", "Sinusoidal ECs"))


# MSCs
msc1.vio <- VlnPlot(stromals, features = "Lepr") + NoLegend()
msc2.vio <- VlnPlot(stromals, features = "Adipoq") + NoLegend()
msc3.vio <- VlnPlot(stromals, features = "Cxcl12") + NoLegend()

msc.violin <- grid.arrange(msc1.vio, msc2.vio, msc3.vio, nrow = 1)
ggsave(plot = msc.violin, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/MSC_ViolinGrid.png", height = 5, width = 15)

# OLCs
olc1.vio <- VlnPlot(stromals, features = "Bglap") + NoLegend()
olc2.vio <- VlnPlot(stromals, features = "Spp1") + NoLegend()
olc3.vio <- VlnPlot(stromals, features = "Sp7") + NoLegend()

olc.violin <- grid.arrange(olc1.vio, olc2.vio, olc3.vio, nrow = 1)
ggsave(plot = olc.violin, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/OLC_ViolinGrid.png", height = 5, width = 15)

# Fibros
fibros1.vio <- VlnPlot(stromals, features = "S100a4") + NoLegend()
fibros2.vio <- VlnPlot(stromals, features = "Fn1") + NoLegend()
fibros3.vio <- VlnPlot(stromals, features = "Dcn") + NoLegend()

fibros.violin <- grid.arrange(fibros1.vio, fibros2.vio, fibros3.vio, nrow = 1)
ggsave(plot = fibros.violin, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Fibros_ViolinGrid.png", height = 5, width = 15)

# Chondros
chondros1.vio <- VlnPlot(stromals, features = "Col2a1") + NoLegend()
chondros2.vio <- VlnPlot(stromals, features = "Sox9") + NoLegend()
chondros3.vio <- VlnPlot(stromals, features = "Acan") + NoLegend()

chondros.violin <- grid.arrange(chondros1.vio, chondros2.vio, chondros3.vio, nrow = 1)
ggsave(plot = chondros.violin, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Chondros_ViolinGrid.png", height = 5, width = 15)

# Pericytes
peris1.vio <- VlnPlot(stromals, features = "Acta2") + NoLegend()
peris2.vio <- VlnPlot(stromals, features = "Myh11") + NoLegend()
peris3.vio <- VlnPlot(stromals, features = "Mcam") + NoLegend()

peris.violin <- grid.arrange(peris1.vio, peris2.vio, peris3.vio, nrow = 1)
ggsave(plot = peris.violin, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/Pericyte_ViolinGrid.png", height = 5, width = 15)

# Endothelial Cells
ecs1.vio <- VlnPlot(stromals, features = "Cdh5") + NoLegend()
ecs2.vio <- VlnPlot(stromals, features = "Cd34") + NoLegend()
ecs3.vio <- VlnPlot(stromals, features = "Pecam1") + NoLegend()
ecs4.vio <- VlnPlot(stromals, features = "Kdr") + NoLegend()
ecs5.vio <- VlnPlot(stromals, features = "Emcn") + NoLegend()

# EC subpopulations - Arterial and Sinusoidal
ecs6.vio <- VlnPlot(stromals, features = "Flt4") + ggtitle("Flt4 (Vegfr-3)") + NoLegend()
ecs7.vio <- VlnPlot(stromals, features = "Ly6a") + ggtitle("Ly6a (Sca-1)") + NoLegend()
ecs8.vio <- VlnPlot(stromals, features = "Cxcl12") + NoLegend()
ecs9.vio <- VlnPlot(stromals, features = "Il6st") + NoLegend()

ecs.violins <- grid.arrange(ecs1.vio, ecs2.vio, ecs3.vio, nrow = 1)
ggsave(plot = ecs.violins, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/ECs_ViolinPlotGrid.png", height = 3, width = 9)

ecs.subtypes.violins <- grid.arrange(ecs6.vio, ecs7.vio, ecs8.vio, ecs9.vio, nrow = 1)
ggsave(plot = ecs.subtypes.violins, filename = "/Users/gagled01/morganLab/single-cell/5TG_Mouse_Rerun/figures/ECSubtypes_ViolinPlotGrid.png", height = 3, width = 12)
```

